accounts/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.views import PasswordResetConfirmView

app_name = 'accounts'

urlpatterns =[
    path('register/', views.CustomRegistrationView.as_view(), name='django_registration_register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='auth_password_reset_confirm'),
    path('profile/', views.AccountsView, name='profile'),
    path('profile/edit/', views.EditProfileView, name='edit-profile'),
    path('profile/delete/', views.DeleteProfileView, name='delete-profile'),
    path("profile/subscription-management/<int:organization_pk>/people/add/", views.OrganizationUserCreateView.as_view(), name="organization_user_add"),
    path('profile/subscription-management/', include('organizations.urls'), name='subscription-management'),
    path('invitations/token-error', views.token_error_view, name='invitations-token-error'),
    path('user-list', views.UserListView.as_view(template_name='accounts/user-list.html'), name='user-list'),
    path('user-list-filtered', views.UserListView.as_view(template_name='accounts/user-list-filtered.html'), name='user-list-filtered'),
    path('superuser-profile-edit/<int:pk>', views.SuperuserProfileEditView.as_view(), name='superuser-profile-edit')
]

api/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path('(?P<version>(v1))/opening/', views.OpeningSet.as_view()),
    re_path('(?P<version>(v1))/opening_slot/', views.OpeningSlotSet.as_view()),
    re_path('(?P<version>(v1))/machine_slot/', views.MachineSlotSet.as_view()),
    re_path('(?P<version>(v1))/training_slot/', views.TrainingSlotSet.as_view()),
    re_path('(?P<version>(v1))/custom_user/', views.CustomUserSet.as_view()),
    re_path('(?P<version>(v1))/subscription/', views.SubscriptionSet.as_view()),
    re_path('(?P<version>(v1))/profile/', views.ProfileSet.as_view()),
]

interlab/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from . import views

from organizations.backends import invitation_backend

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('machines/', include('machines.urls')),
    path('invitations/', include(invitation_backend().get_urls())),
    path('fabcal/', include('fabcal.urls')),
    path('share/', include('share.urls')),
    path('payments/', include('payments.urls')),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path('error-500/', views.error_500, name='error-500'),
    path("", include("newsletter.urls")),
    path("", include("cms.urls")),
    prefix_default_language=False
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += i18n_patterns(
       path(r'^__debug__/', include(debug_toolbar.urls)),
       prefix_default_language=False
    )

accounts/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

import machines

class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)

    def __str__(self):
        return self.first_name + ' ' +  self.last_name + ' <' + self.email + '>'
class SubscriptionCategory(models.Model):
    title = models.CharField(max_length=255)
    price = models.IntegerField() # Swiss Franc
    default_access_number = models.PositiveSmallIntegerField(default=1)
    duration = models.PositiveSmallIntegerField(default=365) # in days
    star_flag = models.BooleanField()
    sort = models.PositiveSmallIntegerField()

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "Subscription Categories"

    def get_display_price(self):
            return "{0:.2f}".format(self.price / 100)

class Subscription(models.Model):
    start = models.DateField()
    end = models.DateField()
    subscription_category = models.ForeignKey(SubscriptionCategory, on_delete=models.CASCADE, null=True)
    access_number = models.PositiveSmallIntegerField()

    def __str__(self):
        if self.subscription_category==None:
            return f"No subscription_category, {self.access_number}, {self.start}, {self.end}"
        return f"{self.subscription_category.title}, {self.access_number}, {self.start}, {self.end}"

class Profile(models.Model):
    PUBLIC_CONTACT_PLATEFORM_CHOICES =[
        ('discord', 'Discord'),
        ('instagram', 'Instagram'),
        ('facebook', 'Facebook'),
        ('linkedin', 'Linkedin'),
        ('envelope', 'e-mail'),
    ]
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    subscription = models.ForeignKey(Subscription, on_delete=models.SET_NULL, blank=True, null=True)
    phone_number = PhoneNumberField(blank=True, null=True, verbose_name=_('Phone number'))
    public_contact_plateform = models.CharField(max_length=255, blank=True, null=True, choices=PUBLIC_CONTACT_PLATEFORM_CHOICES, verbose_name=_('Plublic chanel'))
    public_contact = models.CharField(max_length=255, blank=True, null=True, verbose_name=_('Public contact'))

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}, ({self.user.username})"

    @property 
    def get_training_validations(self):
        return self.trainingvalidation_set.all()

    @property 
    def is_subscription_valid(self):
        if self.subscription:
            return date.today() >= self.subscription.start and date.today() <= self.subscription.end
        else:
            return False

class SuperUserStatus(models.Model):
    status = models.CharField(max_length=255)

    def __str__(self):
        return self.status

class SuperUserProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="profile")
    about_me = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("About me"))
    status = models.ManyToManyField(SuperUserStatus, verbose_name=_("Status"), blank=True)
    trainer = models.ManyToManyField("machines.Training", verbose_name=_("Trainer"), blank=True)
    technique = models.ManyToManyField("machines.Workshop", verbose_name=_("Technique"), blank=True)
    software = models.ManyToManyField("machines.Software", verbose_name=_("Software"), blank=True)
    machine_category =  models.ManyToManyField("machines.MachineCategory", verbose_name=_("Machine category"), blank=True)

    def __str__(self):
        return str(self.user)

from cms.models import CMSPlugin
class SuperUserListPluginModel(CMSPlugin):
    pass

accounts/views.py
import datetime
from itertools import chain
from operator import attrgetter
import dateparser

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.sessions.models import Session
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Q, OuterRef, Exists
from django.http import HttpResponse
from django.template import loader
from django.utils.translation import gettext as _
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic.base import TemplateView


from fabcal.models import EventSlot, OpeningSlot, TrainingSlot, MachineSlot, RegistrationEventSlot
from machines.models import TrainingValidation

from .forms import EditUserForm, EditProfileForm, CustomOrganizationUserAddForm, CustomRegistrationForm, CustomAuthenticationForm, SuperuserProfileEditForm
from .models import Profile

from organizations.views.base import BaseOrganizationUserCreate
from organizations.views.base import BaseOrganizationUserDelete
from organizations.views.mixins import OwnerRequiredMixin

from django_registration.backends.activation.views import RegistrationView
from django_registration import signals

from newsletter.views import register_email, get_contact, update_contact
from interlab.views import CustomFormView

class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm

class CustomRegistrationView(RegistrationView):
    template_name = 'registration/registration_form.html'
    form_class = CustomRegistrationForm

    def register(self, form):
        new_user = self.create_inactive_user(form)

        # Add user to newsletter list
        if form.cleaned_data['newsletter']: 
            register_email(form.cleaned_data['email'])
        
        signals.user_registered.send(
            sender=self.__class__, user=new_user, request=self.request
        )
        return new_user

@login_required
def AccountsView(request):
    user = request.user
    template = loader.get_template('accounts/profile.html')

    today = datetime.date.today()

    # Subquery to check if the user has registrations for the event slot
    registration_event_slot = RegistrationEventSlot.objects.filter(
        event_slot=OuterRef('pk'),
        event_slot__end__gte=today,
        user=request.user
    )

    context = {
        'page_title': "My account",
        'user': user,
        'slots': sorted(chain(
            TrainingSlot.objects.filter(user=request.user, end__gte=datetime.date.today()),
            TrainingSlot.objects.filter(registrations=request.user, end__gte=datetime.date.today()),
            EventSlot.objects.filter(user=request.user, end__gte=datetime.date.today()),
            EventSlot.objects.filter(Exists(registration_event_slot)),
            OpeningSlot.objects.filter(user=request.user, end__gte=datetime.date.today()), 
            MachineSlot.objects.filter(user=request.user, end__gte=datetime.date.today()),
        ),
        key=attrgetter('start')
        )
    }

    (profile, _) = Profile.objects.get_or_create(user=user)
    if profile.subscription is not None:
        context['subscription'] = profile.subscription
        context['subscription_category']=profile.subscription.subscription_category_id
        
    return HttpResponse(template.render(context, request))

@login_required
def EditProfileView(request):
    template = 'accounts/profile_edit.html'

    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            # Check if profile has newsletter
            contacts = get_contact()
            mail_list = [contact['email'] for contact in contacts['data']['data']]
            if 'email' in user_form.changed_data:
                old_email = user_form.initial['email']
                if old_email in mail_list:
                    user_id = next((contact['id'] for contact in contacts['data']['data'] if contact['email'] == old_email), None)
                    if user_id is not None:
                        new_email = user_form.cleaned_data['email']
                        update_contact(user_id, new_email)
                        messages.success(request, _("Your newsletter registration has been updated successfully with the email address: ") + new_email)

            user_form.save()
            profile_form.save()

            messages.success(request, _("Your profile has been updated successfully"))
            return redirect('accounts:profile')
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)

    context = {
        "edit_user_form": user_form,
        "edit_profile_form": profile_form
    }

    return render(request, template, context)

@login_required
def DeleteProfileView(request):
    template = 'accounts/profile_delete.html'
    context = {
        'page_title': "Delete my profile" 
    }
    if request.method == 'POST':
        user = request.user
        user.is_active = False
        user.save()
        messages.success(request, _("Your account has been successfully deleted") )
        [s.delete() for s in Session.objects.all() if s.get_decoded().get('_auth_user_id') == user.id]
        return redirect('/')

    return render(request, template, context)

class OrganizationUserDeleteView(OwnerRequiredMixin, LoginRequiredMixin, BaseOrganizationUserDelete):
    def post(self, request, *args, **kwargs):

        # Remove user from organization
        self.organization.remove_user(self.organization_user.user)

        # Remove subscription of the user
        try:
            profile = Profile.objects.get(user_id=self.organization_user.user_id)
            profile.subscription = None
            profile.save()
        except Profile.DoesNotExist:
            pass
        
        if self.organization_user.user.first_name:
            messages.success(request, self.organization_user.user.first_name + self.organization_user.user.last_name + _(" has been removed successfully from the team.") )
        else:
            messages.success(request, self.organization_user.user.email + _(" has been removed successfully from the team.") )
        return redirect('organization_detail', organization_pk=request.user.organizations_organization.first().pk)

class OrganizationUserCreateView(OwnerRequiredMixin, LoginRequiredMixin, BaseOrganizationUserCreate):
    form_class = CustomOrganizationUserAddForm

def token_error_view(request): 
    template = 'organizations/invitations_token_error.html'
    return render(request, template) 

class UserListView(LoginRequiredMixin, TemplateView):
    number_of_item = 10

    def get(self, *args, **kwargs):
        if not self.request.user.groups.filter(name = 'superuser').exists():
            raise PermissionDenied
        else:
            template = self.template_name
            context = self.get_context_data()
            return render(self.request, template, context)  

    def post(self, *args, **kwargs):
        template = self.template_name
        context = self.get_context_data()
        return render(self.request, template, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = self.find_user(self.request.POST.get('search'))
        users = self.get_page_obj(self.request, users, self.number_of_item)
        context['users'] = users
        return context

    def get_page_obj(self, request, list_of_objects, number_of_item):
        paginator = Paginator(list_of_objects, number_of_item)
        page_number = request.GET.get('page')
        return paginator.get_page(page_number)

    def find_user(self, query):
        qs = get_user_model().objects.all()
        if query:
            for term in query.split():
                qs = qs.filter( 
                    Q(first_name__icontains = term) | 
                    Q(last_name__icontains = term) |
                    Q(email__icontains = term)
                    )
        return qs

class SuperuserProfileEditView(LoginRequiredMixin, CustomFormView):
    template_name = 'accounts/superuser-profile-edit.html'
    form_class = SuperuserProfileEditForm

    def get_success_url(self):
        return reverse('accounts:user-list')

    def get_initial(self):
        initial = super().get_initial()
        self.user = get_user_model().objects.get(pk=self.kwargs['pk'])
        if self.user.profile is not None \
            and self.user.profile.subscription is not None \
            and self.user.profile.subscription.subscription_category is not None:
            initial['subscription_category'] = self.user.profile.subscription.subscription_category
            initial['start'] = self.user.profile.subscription.start
            initial['end'] = self.user.profile.subscription.end

        if self.user.profile is not None:
             initial['training'] = [t.training.pk for t in TrainingValidation.objects.filter(profile=self.user.profile)]

        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.user

        if context['form'].initial.get('subscription_category', None) is not None:
            context['start'] = context['form'].initial['start']
            context['end'] = context['form'].initial['end']
        else:
            today = datetime.datetime.today()
            context['start'] = today
            context['end'] = today + datetime.timedelta(days=365)
        return context
    
    def form_invalide(self):
        pass

accounts/templates/organizations/icon_person_pending_fill.html
<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="img-sm" viewBox="0 0 16 16">
    <path d="m 1,14 c 0,0 -1,0 -1,-1 0,-1 1,-4 6,-4 5,0 6,3 6,4 0,1 -1,1 -1,1 z M 6,8 A 3,3 0 1 0 6,2 3,3 0 0 0 6,8 Z"/>
    <g transform="matrix(1.1385034,0,0,1.1385034,-1.5542001,-0.99846884)">
        <path d="m 13.261719,5.1738281 c -0.01048,4.196e-4 -0.02083,7.316e-4 -0.03125,0.00195 -0.153504,0.015856 -0.294342,0.1259614 -0.345703,0.2714844 -0.05136,0.145523 -0.01189,0.3190377 0.09766,0.4277344 l 0.933594,0.9355469 H 11.09375 c -0.214709,-8.49e-4 -0.409466,0.1934938 -0.410156,0.4082031 6.9e-4,0.2147093 0.195447,0.4090521 0.410156,0.4082031 h 2.822266 L 12.982422,8.5625 a 0.13752541,0.13752541 0 0 0 -0.0059,0.00781 c -0.135013,0.1548527 -0.12574,0.4133217 0.01953,0.5585937 0.145272,0.1452721 0.403741,0.1545448 0.558594,0.019531 a 0.13752541,0.13752541 0 0 0 0.0078,-0.00586 l 1.634766,-1.6328125 c 0.153135,-0.1519137 0.153135,-0.4301175 0,-0.5820312 L 13.5625,5.296875 C 13.485542,5.2181779 13.375693,5.1729037 13.265625,5.1738281 a 0.13752541,0.13752541 0 0 0 -0.0039,0 z" />
    </g>
</svg>  

accounts/templates/organizations/invitations_token_error.html
{% extends 'forms/base_forms.html' %}
{% load i18n %}

{% block content_form_img %}
    <i class="bi bi-envelope-slash-fill mb-5 img-form-logo mx-auto d-block text-red"></i>
{% endblock %}

{% block content_form %}
<h2>{% translate 'Your URL may have expired.' %}</h2>
<div class="d-grid">
    <a class="btn btn-primary my-4" href="/" role="button">{% trans "Home" %}</a>
</div>
{% endblock %}

accounts/templates/organizations/organization_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load org_tags %}

{% block content %}
<div class="row">
    <div class="col-md-4 py-5 d-none d-md-block">
        {% include 'accounts/nav.html' %}
    </div>
    <div class="col-md-8 p-5">
        <div class="text-center">
            <div class="img-head mx-auto">
                <i class="bi bi-people-fill"></i>
            </div>    
            <h2> {{ user.profile.subscription.subscription_category.title }} </h2>
            <h3>{{ organization.name }}</h3>
            <p> {% trans "valid until"|capfirst %} {{ user.profile.subscription.end|date:'d.m.Y' }}  </br>
            {% trans 'Access number' %} : {{ user.profile.subscription.access_number }} </p>
        </div>
        <hr>
        <h2>{% trans 'Your team members' %}</h2> 

        {% organization_users organization %}            
              
    </div>
    <div class="col-md-4 py-5 d-md-none">
        <hr>
        {% include 'accounts/nav.html' %}
    </div>
</div>

{% endblock content %}

accounts/templates/organizations/organization_list.html
{% include 'organizations/organization_detail.html' %}

accounts/templates/organizations/organization_users.html
{% load i18n static %}

{% for organization_user in organization_users %}

{% if user != organization_user.user or organization_user.is_owner %}
<a class="text-blue" href="{% url "organization_user_delete" organization.pk organization_user.user.pk %}">
{% endif %}    
    <div class="row">
        <div class="col-2 my-auto text-center">
                {% if organization_user.user.is_active %}
                    <i class="bi bi-person-check-fill img-sm"></i>
                {% else %}          
                    {% include 'organizations/icon_person_pending_fill.html' %}
                {% endif %}
        </div>
        <div class="col-8 my-auto">
            <p class="my-auto">
                {% if organization_user.user.first_name %}
                    {{ organization_user.user.first_name }} {{ organization_user.user.last_name }} 
                {% else %} 
                    {{ organization_user.user.email }}
                {% endif %}
                <span class="fs-6">
                    {% if user == organization_user.user %} <span class="badge rounded-pill text-bg-info-light">{% trans "This is you" %}!</span> {% endif %}
                </span>
                 </br>
                <span class="fs-6">
                    {% if organization_user.user.is_active %}
                        <span class="badge rounded-pill text-bg-success-light"> <i class="bi bi-check-circle-fill"></i> {% trans 'activated' %} </span>
                    {% else %}  
                        <span class="badge rounded-pill text-bg-info-light"> <i class="bi bi-arrow-right-circle-fill"></i> {% trans 'invitation sent' %} </span>
                    {% endif %}
                </span>
            </p>
        </div>
        <div class="col-2 my-auto">
            {% if user != organization_user.user  or organization_user.is_owner %}
            <h1><i class="bi bi-trash3"></i></h1>
            {% endif %}
        </div>
    </div>
{% if user != organization_user.user or organization_user.is_owner %} 
</a>
{% endif %}  

{% endfor %}

{% if organization_users.count < user.profile.subscription.access_number  %}
        
<a class="text-blue" href="{% url "accounts:organization_user_add" organization.pk %}">
<div class="row">
    <div class="col-2 text-center">
        <i class="bi bi-person-plus-fill img-sm" ></i>
    </div>
    <div class="col-8 my-auto">
        {% trans 'Invite a new user' %}
    </div>
    <div class="col-2">
        <h1><i class="bi bi-arrow-right-square"></i></h1>
    </div>
</div>
</a>
        
{% endif %}

accounts/templates/organizations/organizationuser_confirm_delete.html
{% extends "forms/base_forms.html" %}
{% load i18n %}

{% block content_form_img %}
<i class="bi bi-person-x-fill mb-5 img-form-logo mx-auto d-block text-red"></i>
{% endblock %}

{% block content_form %}
<h1>{% trans 'Are you sure you want to remove ' %} 
    {% if organization_user.user.first_name != '' %}
        {{ organization_user.user.first_name }} {{ organization_user.user.last_name }}
    {% else %}
        {{ organization_user.user.email }}
    {% endif %}
    {% trans 'from the team' %} {{ organization_user.organization.name }}</h1>

{% include "forms/base_submit_button.html" with submit_btn="Yes, I'm sure" %}

<div class="text-center mt-5 text-red">

    <a href="profile/delete_done"></a>
  </div>
    
{% endblock content_form %}

accounts/templates/organizations/organizationuser_detail.html
{% include 'organizations/organizationuser_form.html' %}

accounts/templates/organizations/organizationuser_form.html
{% extends "forms/base_forms.html" %}
{% load i18n crispy_forms_tags %}

{% block content_form %}

{% if organization_user %}

<h1>{% trans "Update your profile" %}</h1>
{% if user == organization_user.user %}{% trans "This is you" %}!{% endif %}

<a href="{% url "organization_user_delete" organization.pk organization_user.user.pk %}">{% trans "Delete" %}</a>

{% else %}

<h1> {% trans 'Invite a member to join the team' %} {{ organization }}</h1>

<form action="." method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <div class="col">
        <input class="btn btn-primary d-block mx-auto" type="submit" value="{% trans 'Send invitation' %}">
    </div>
</form>

{% endif %}


{% endblock %}

accounts/templates/organizations/organizationuser_list.html
{% include 'organizations/organization_detail.html' %}

accounts/templates/organizations/register_form.html
{% extends "forms/base_forms.html" %}
{% load i18n crispy_forms_tags %}

{% block html_class %} {% endblock %}

{% block content_form %}

<h2>{% trans 'Join the team' %} {{ organization.name }}</h2>

<form action="." method="post" enctype="multipart/form-data">{% csrf_token %}
    {% csrf_token %}
    {{ form | crispy }}
    <div class="col">
        <input class="btn btn-primary d-block mx-auto" type="submit" value="{% trans 'Subscribe' %}">
    </div>
</form>

{% endblock %}