api/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path('(?P<version>(v1))/opening/', views.OpeningSet.as_view()),
    re_path('(?P<version>(v1))/opening_slot/', views.OpeningSlotSet.as_view()),
    re_path('(?P<version>(v1))/machine_slot/', views.MachineSlotSet.as_view()),
    re_path('(?P<version>(v1))/training_slot/', views.TrainingSlotSet.as_view()),
    re_path('(?P<version>(v1))/custom_user/', views.CustomUserSet.as_view()),
    re_path('(?P<version>(v1))/subscription/', views.SubscriptionSet.as_view()),
    re_path('(?P<version>(v1))/profile/', views.ProfileSet.as_view()),
]

fabcal/urls.py
from django.urls import path
from . import views

app_name = 'fabcal'

urlpatterns = [
    path('openingslot/create/<str:start>/<str:end>/', views.OpeningSlotCreateView.as_view(), name='openingslot-create'),
    path('openingslot/update/<int:pk>/', views.OpeningSlotUpdateView.as_view(), name='openingslot-update'),
    path('openingslot/delete/<int:pk>/', views.OpeningSlotDeleteView.as_view(), name='openingslot-delete'),
    path('machineslot/update/<int:pk>/', views.MachineSlotUpdateView.as_view(), name='machineslot-update'),
    path('machineslot/delete/<int:pk>/', views.MachineSlotDeleteView.as_view(), name='machineslot-delete'),
    path('trainingslot/create/<str:start>/<str:end>/', views.TrainingSlotCreateView.as_view(), name='trainingslot-create'),
    path('trainingslot/update/<int:pk>/', views.TrainingSlotUpdateView.as_view(), name='trainingslot-update'),
    path('trainingslot/delete/<int:pk>/', views.TrainingSlotDeleteView.as_view(), name='trainingslot-delete'),
    path('trainingslot/register/create/<int:pk>/', views.TrainingSlotRegistrationCreateView.as_view(), name='trainingslot-register'),
    path('trainingslot/register/delete/<int:pk>/', views.TrainingSlotRegistrationDeleteView.as_view(), name='trainingslot-unregister'),
    path('eventslot/<int:pk>/', views.EventSlotDetailView.as_view(), name='eventslot-detail'),
    path('eventslot/create/<str:start>/<str:end>/', views.EventSlotCreateView.as_view(), name='eventslot-create'),
    path('eventslot/update/<int:pk>/', views.EventSlotUpdateView.as_view(), name='eventslot-update'),
    path('eventslot/delete/<int:pk>/', views.EventSlotDeleteView.as_view(), name='eventslot-delete'),
    path('eventslot/register/create/<int:pk>/', views.EventSlotRegistrationCreateView.as_view(), name='eventslot-register'),
    path('eventslot/register/delete/<int:pk>/', views.EventSlotRegistrationDeleteView.as_view(), name='eventslot-unregister'),
    path('download-ics-file/<str:summary>/<str:start>/<str:end>/', views.downloadIcsFileView.as_view(), name='download-ics-file'),
    path('machine/reservation/future/', views.MachineFutureReservationListView.as_view(), name='machine-reservation-future'),
    path('machine/reservation/past/', views.MachinePastReservationListView.as_view(), name='machine-reservation-past')
]

interlab/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from . import views

from organizations.backends import invitation_backend

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('machines/', include('machines.urls')),
    path('invitations/', include(invitation_backend().get_urls())),
    path('fabcal/', include('fabcal.urls')),
    path('share/', include('share.urls')),
    path('payments/', include('payments.urls')),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path('error-500/', views.error_500, name='error-500'),
    path("", include("newsletter.urls")),
    path("", include("cms.urls")),
    prefix_default_language=False
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += i18n_patterns(
       path(r'^__debug__/', include(debug_toolbar.urls)),
       prefix_default_language=False
    )

fabcal/views.py
from datetime import datetime, timedelta
from babel.dates import format_datetime

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ValidationError, PermissionDenied
from django.http import HttpResponse, QueryDict, HttpResponseForbidden
from django.shortcuts import redirect
from django.template import loader
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView

from interlab.views import CustomFormView
from machines.models import Machine

from .forms import OpeningSlotCreateForm
from .forms import OpeningSlotUpdateForm
from .forms import MachineSlotUpdateForm
from .forms import TrainingSlotCreateForm
from .forms import TrainingSlotUpdateForm
from .forms import TrainingSlotRegistrationCreateForm
from .forms import TrainingSlotRegistrationDeleteForm
from .forms import EventSlotCreateForm
from .forms import EventSlotUpdateForm
from .forms import EventSlotRegistrationCreateForm

from .models import OpeningSlot, EventSlot, TrainingSlot, MachineSlot, RegistrationEventSlot
from .mixins import SuperuserRequiredMixin


class UserView(LoginRequiredMixin, SuccessMessageMixin, CustomFormView):
    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
            
        # Pass the user object to the form's constructor
        return form_class(self.request.user, **self.get_form_kwargs())

class CreateSlotView(UserView, CreateView):
    def get_initial(self):
        initial = super().get_initial()
        
        params = {}
        for i in ['start', 'end']:
            params[i] = datetime.fromtimestamp(int(self.kwargs.get(i))/1000)

        initial['date'] = params['start'].strftime('%Y-%m-%d')
        initial['start_time'] = params['start'].strftime('%H:%M')
        initial['end_time'] = params['end'].strftime('%H:%M')
        return initial

class UpdateSlotView(UserView, UpdateView):

    def get_initial(self):
        initial = super().get_initial()
        initial['start'] = self.object.start
        initial['end'] = self.object.end

        initial['date'] = self.object.start.strftime('%Y-%m-%d')
        initial['start_time'] = self.object.start.strftime('%H:%M')
        initial['end_time'] = self.object.end.strftime('%H:%M')
        return initial

class RegisterSlotView(UserView):
    pass

class DeleteSlotView(LoginRequiredMixin, DeleteView):
    def get_success_url(self):
        return reverse_lazy("accounts:profile")

    def dispatch(self, request, *args, **kwargs):
        slot = self.get_object()
        # Check if the request user is not the same as the machine slot user
        if request.user != slot.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        language_code = settings.LANGUAGE_CODE
        context.update({ 
            'date': format_datetime(self.object.start, "EEEE d MMMM y", locale=language_code),
            'start': format_datetime(self.object.start, "H:mm", locale=language_code),
            'end': format_datetime(self.object.end, "H:mm", locale=language_code),
        })
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.success(request, self.sucess_message % self.get_context_data())
            return redirect(self.get_success_url())
        except ValidationError as e:
            try: 
                request.session['error_code'] = getattr(e, 'code')
            except AttributeError:
                request.session['error_code'] = None

            messages.error(request, _(e.message))
            return redirect(request.META.get('HTTP_REFERER', '/'))

class OpeningSlotView(SuperuserRequiredMixin):
    model = OpeningSlot

    success_message = _("Your opening has been successfully %(action)s on %(date)s from %(start_time)s to %(end_time)s </br> "
                 "<a href=\"/fabcal/download-ics-file/%(opening_title)s/%(start)s/%(end)s\"> "
                 "<i class=\"bi bi-file-earmark-arrow-down-fill\"> </i> Add to my calendar</a>")

    def get_success_message(self, cleaned_data):
        if issubclass(self.__class__, CreateView):
            action = _('created')
        elif issubclass(self.__class__, UpdateView):
            action = _('updated')

        return mark_safe(
                    self.success_message % dict(
                        action=action,
                        date=self.object.formatted_start_date,
                        start_time=self.object.formatted_start_time,
                        end_time=self.object.formatted_end_time,
                        opening_title=self.object.opening.title,
                        start=self.object.start,
                        end=self.object.end
                    )
                )       

    def form_invalid(self, form):       
        updated_data = QueryDict(mutable=True)
        updated_data.update(form.data)

        for error in form.errors.get('__all__').data:

            if error.code == 'conflicting_openings':        
                conflicting_openings = error.params.get('conflicting_openings')

                # Calculate the new start and end time based on the existing opening
                for conflicting_opening in conflicting_openings:

                    # Determine the start time of the new opening based on the conflicting opening
                    # If the new opening starts before the conflicting opening, use the start time of the new opening
                    # Otherwise, use the end time of the conflicting opening
                    if form.cleaned_data['start_time'] < conflicting_opening.start.time():
                        start_time = form.cleaned_data['start_time']
                    else:
                        start_time = conflicting_opening.end.time()

                    # Determine the end time of the new opening based on the conflicting opening
                    # If the new opening ends after the conflicting opening, use the end time of the new opening
                    # Otherwise, use the start time of the conflicting opening
                    if form.cleaned_data['end_time'] > conflicting_opening.end.time():
                        end_time = form.cleaned_data['end_time']
                    else:
                        end_time = conflicting_opening.start.time()


                # Set the form data to the new start and end time
                updated_data['start_time'] = forms.TimeField().prepare_value(start_time)
                updated_data['end_time'] = forms.TimeField().prepare_value(end_time)

                # Call form.add_error to add the error to the start_time field
                form.add_error('start_time', error)


            elif error.code == 'conflicting_reservation':
                updated_data['start_time'] = forms.TimeField().prepare_value(
                    datetime.strptime(form.initial['start_time'], '%H:%M').time()
                    )
                updated_data['end_time'] = forms.TimeField().prepare_value(
                    datetime.strptime(form.initial['end_time'], '%H:%M').time()
                    )

        # Update form data
        form.data = updated_data

        # Return the invalid form
        return self.render_to_response(self.get_context_data(form=form))

class OpeningSlotCreateView(OpeningSlotView, CreateSlotView):
    form_class = OpeningSlotCreateForm
    success_url = '/schedule'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_btn'] = _('Create opening')
        return context

class OpeningSlotUpdateView(OpeningSlotView, UpdateSlotView):
    form_class = OpeningSlotUpdateForm

    def get_success_url(self):
        return reverse_lazy("accounts:profile")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_btn'] = _('Update opening')
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial['machines'] = [i.pk for i in self.object.get_machine_list]
        return initial

class OpeningSlotDeleteView(SuperuserRequiredMixin, DeleteSlotView):
    model = OpeningSlot
    success_url = '/schedule'
    sucess_message = _("Your opening on %(date)s from %(start)s to %(end)s has been successfully deleted")

class MachineSlotUpdateView(UpdateSlotView):
    model = MachineSlot
    form_class = MachineSlotUpdateForm

    success_message = _('You successfully booked the machine %(machine)s during %(duration)s minutes on %(start_date)s from %(start_time)s to %(end_time)s')

    def get_success_url(self):
        return reverse_lazy("accounts:profile")

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
                    machine=self.object.machine.title,
                    duration=self.object.get_duration,
                    start_date=self.object.formatted_start_date,
                    start_time=self.object.formatted_start_time,
                    end_time=self.object.formatted_end_time,
                )

    def dispatch(self, request, *args, **kwargs):
        """
        Check if the user's profile is in the trained profile list of a specific machine. 
        If not, display an error message and redirect the user to the training page for that machine category.
        """

fabcal/templates/fabcal/event_(un)registration_form.html
{% extends "forms/base_forms.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}

{% block content_form_img %}
<img src="{{object.event.img.url}}" class="img img-fluid rounded" alt="{{object.event.title}}">
{% endblock %}

{% block content_form %}
<h3>{{object.event.title}}</h3>
{% include 'fabcal/event_info.html' %}

<form action="
    {% if 'unregister' in view.request.path %}
        {% url 'fabcal:event-unregister' object.pk %}
    {% else %}
        {% url 'fabcal:event-register' object.pk %}{%endif%}"
    method="POST">
    {% csrf_token %}

    {% if 'unregister' in view.request.path %}
        {% include "forms/base_submit_button.html" with submit_btn="Unregister" %}
    {% else %}
        {% include "forms/base_submit_button.html" with submit_btn="Register" %}
    {% endif %}
</form>

{% endblock content_form %}

fabcal/templates/fabcal/event_card.html
{% load i18n %}
<div class="col col-sm-12 col-md-6 col-xl-4 grid-item">
    <div class="card card-border-red">
        <img src="/media/{{event_slot.event.photo}}" class="card-img-top" alt="{{event_slot.event.title}}">
        <div class="card-body">
            <h3 class="card-title"> {{event_slot.event.title}}</h3>
            <p class="card-text"> {{event_slot.event.lead}} </p>
            {% include 'fabcal/event_info_datetime.html' with format_info_datetime=event_slot.format_info_datetime%}
            <div class="text-center">
                <a href="{% url 'fabcal:eventslot-detail' event_slot.pk %}" type="button" class="btn btn-outline-primary">
                    <i class="bi bi-info-circle pe-2"></i> {% trans "More informations" %}
                </a>
            </div>
        </div>
    </div>
</div>

fabcal/templates/fabcal/event_create_or_update_form.html
{% extends "forms/base_forms.html" %}
{% load i18n crispy_forms_tags %}
{% load render_bundle from webpack_loader %}

{% block header %}
{{ form.media }}
{% endblock header %}

{% block content_form_img %}
<i class="bi bi-calendar-plus mb-5 img-form-logo mx-auto d-block"></i>
{% endblock %}

{% block content_form %}

<form method="POST">

    {% csrf_token %}


    <div class="form-group">

        <div class="mb-3">
            <label for="{{ form.event.id_for_label }}">{{ form.event.label_tag }}</label>
            {{ form.event }}
            {{ form.event.errors }}
        </div>

        <div class="mb-3">
            <label for="{{ form.opening.id_for_label }}">{{ form.opening.label_tag }}</label>
            {{ form.opening }}
            {{ form.opening.errors }}
        </div>

        {%include './form/select_machines.html'%}

        <div data-app>
            <div id="vue">
                <div class="mb-3">
                    {% trans "Start" %}<br>
                    <v-row>
                        <v-col cols="8">
                            <date-picker init-date={{start|date:"Y-m-d"}} input-name="start_date"
                                label={% trans "Date" %}>
                            </date-picker>
                        </v-col>
                        <v-col cols="4">
                            <time-picker init-time={{start|date:"H:i"}} input-name="start_time"
                                label={% trans "Time" %}>
                            </time-picker>
                        </v-col>
                    </v-row>
                    {% trans "End" %}<br>
                    <v-row>
                        <v-col cols="8">
                            <date-picker init-date={{end|date:"Y-m-d"}} input-name="end_date" label={% trans "Date" %}>
                            </date-picker>
                        </v-col>
                        <v-col cols="4">
                            <time-picker init-time={{end|date:"H:i"}} input-name="end_time" label={% trans "Time" %}>
                            </time-picker>
                        </v-col>
                    </v-row>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <label for="{{ form.price.id_for_label }}">{{ form.price.label_tag }}</label>
            {{ form.price }}
            {{ form.price.errors }}
        </div>

        <div class="mb-3">
            <label for="{{ form.comment.id_for_label }}">{{ form.comment.label_tag }}</label>
            {{ form.comment }}
            {{ form.comment.errors }}
        </div>

        <div class="row mb-3">
            <div class="col">
                {{ form.has_registration.label_tag }}
            </div>
            <div class="col">
                <div class="form-check form-switch">
                    <input class="form-check-input float-end" type="checkbox" role="switch"
                        id={{form.has_registration.auto_id}} name="has_registration"
                        {% if form.has_registration.value %}checked{% endif %}>
                </div>
            </div>
        </div>
        <div class="mb-3">
            {{ form.registration_limit.label_tag }}
            <input class="form-control" id={{form.registration_limit.auto_id}} name="registration_limit" placeholder=""
                type="number" min="0"
                value={% if form.registration_limit.value %}{{ form.registration_limit.value }}{% endif %}>
            </input>
            {{ form.registration_limit.errors }}
            <small>{{ form.registration_limit.help_text }}</small>
        </div>
    </div>
    
    {% include 'forms/base_submit_button.html'%}

</form>
{% endblock content_form %}

{% block js_footer %}
{% render_bundle 'vue' 'js' %}
{% endblock js_footer %}

fabcal/templates/fabcal/event_info.html
{% load i18n fabcal_tags %}

<div class="row">

    <div class="col-12 {% if "detail" in view.template_name_suffix %}col-sm-6{% endif %}">
        {% include 'fabcal/event_info_datetime.html' with event_slot=object %}
    </div>

    {% if object|is_onsite %}
    <div class="col-12 {% if "detail" in view.template_name_suffix %}col-sm-6{% endif %}">
        <div class="row">
            <div class="col-2 text-end pe-0">
                <h4><i class="bi bi-wallet2"></i></h4>
            </div>
            <div class="col-10 ">
                <h4>{% trans "Price" %}</h4>
                <p>{{object.price}}</p>
            </div>
        </div>
    </div>
    {% endif %}

    <div class="col-12 {% if "detail" in view.template_name_suffix %}col-sm-6{% endif %}">
        <div class="row">
            <div class="col-2 text-end pe-0">
                <h4><i class="bi bi-geo-alt"></i></h4>
            </div>
            <div class="col-10 ">
                <h4>{% trans "Location" %}</h4>
                <p>{{object.event.location}}</p>
            </div>
        </div>
    </div>

</div>

fabcal/templates/fabcal/event_info_datetime.html
{% load i18n %}

<div class="row">
    <div class="col-2 text-end pe-0">
        <h4><i class="bi bi-clock"></i></h4>
    </div>
    <div class="col-10 ">
        <h4>{% trans "Date and schedule" %}</h4>
        <p>
            {{event_slot.start|date:"l j F Y"|capfirst}}<br>
            {{event_slot.start|date:"H:i"}} - {{event_slot.end|date:"H:i"}}
        </p>
    </div>
</div>

fabcal/templates/fabcal/event_registration_button.html
{% load i18n fabcal_tags %}

<div class='row text-center'>
    <div class='col'>
    {% if object.registration_required %}
        {% if object.registration_type == 'onsite' %}
            {% if object|can_unregister:request.user %}
                <a href="{% url 'fabcal:eventslot-unregister' registration_id %}" class="btn btn-primary">
                    <i class="bi bi-calendar2-x pe-2"></i> {% trans "Unregister" %}
                </a>
            {% elif object|cannot_unregister:request.user %}
                <button class="btn btn-primary" disabled>
                    <i class="bi bi-calendar2-x pe-2"></i> {% trans "Unregister" %}
                </button><br>
                <small class='text-red'>
                    {% trans "Sorry, you can not unregister 24h before the start of the event" %}
                </small>
            {% elif object|no_registration_limit %}
                <a href="{% url 'fabcal:eventslot-register' object.pk %}" class="btn btn-primary">
                    <i class="bi bi-plus-circle pe-2"></i> {% trans "Register" %}
                </a>
            {% elif object|registration_disabled %}
                <button class="btn btn-primary" disabled>
                    <i class="bi bi-calendar2-x pe-2"></i> {% trans "Sold out" %}
                </button>
            {% else %}
                <a href="{% url 'fabcal:eventslot-register' object.pk %}" class="btn btn-primary">
                    <i class="bi bi-plus-circle pe-2"></i> {% trans "Register" %}
                </a>
                </br>
                <small>{% blocktrans with available_registration=object.available_registration%}still {{available_registration}} places available !{% endblocktrans %}</small>
            {% endif %}
        {% elif object.registration_type == 'external' %}
            {% if '@' in object.external_registration_link %}
                <a href="mailto:{{ object.external_registration_link }}" class="btn btn-primary" target="_blank">
                    <i class="bi bi-envelope pe-2"></i> {% trans "Register" %}
                </a>
            {% else %}
                <a href="{{ object.external_registration_link }}" class="btn btn-primary" target="_blank">
                    <i class="bi bi-box-arrow-up-right pe-2"></i> {% trans "Register" %}
                </a>
            {% endif %}
        {% endif %}
    {% endif %}
    </div>
</div>

fabcal/templates/fabcal/eventslot_detail.html
{% extends 'base.html' %}
{% load i18n interlab_tags %}

{% block content %}
{% if request.user|has_group:"superuser" %}
<div class="row">
    <div class="col text-end">
        <a href="{% url 'fabcal:eventslot-delete' object.pk %}"
            class="btn btn-outline-primary pe-2 {%if object.regristration.all%} disabled {%endif%}">
            <i class="bi bi-trash3 pe-1"></i> {% trans "Delete" %}
        </a>
        <a href="{% url 'fabcal:eventslot-update' object.pk %}" class="btn btn-outline-primary">
            <i class="bi bi-pencil pe-1"></i> {% trans "Edit" %}
        </a>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-md-6">
        <h1>{{object.event.title}}</h1>
        <h4>{{object.event.lead}}</h4>
        <div class="d-none d-md-block">
            <p>{{object.event.desc}}</p>
            {% include 'fabcal/event_registration_list.html' %}
        </div>
    </div>

    <div class="col-md-6">
        <img src="/media/{{object.event.photo}}" class="card-img-top mb-4" alt="{{object.event.title}}">
        <div class="d-md-none">
            {% include 'fabcal/event_info.html' %}
            {% include 'fabcal/event_registration_button.html' %}
            <p class="mt-5">{{object.event.desc}}</p>
            {% include 'fabcal/event_registration_list.html' %}
        </div>

        <div class="d-none d-md-block">
            {% include 'fabcal/event_registration_button.html' %}
            {% include 'fabcal/event_info.html' %}

        </div>
    </div>
</div>

{% endblock content %}

fabcal/templates/fabcal/machineslot_form.html
{% extends "forms/base_forms.html" %}
{% load i18n crispy_forms_tags training_extras %}
{% load render_bundle from webpack_loader %}

{% block header %}
{{ form.media }}
{% endblock header %}

{% block content_form_img %}
<img class="card-img pb-4" src="{{object.machine.photo.url}}"  alt="{{machine}}">
{% endblock %}

{% block content_form %}
<div class="text-center">
    <h3> {% trans "Choose your schedule !" %} </h3>

    <p>{{object.start|date:"l j F Y"|capfirst}} </br>
        <span class='badge align-middle' style="color:{{object.opening_slot.opening.color}};background-color:{{object.opening_slot.opening.background_color}}">
            {{object.opening_slot.opening.title}} - {{object.opening_slot.user.first_name}}
        </span >
    </p>

    {% if object.machine.category.name == '3D' %} <h4> {% trans "Start" %} </h4> {% endif %}

</div>

<form action="." method="POST">
    {% csrf_token %}
    <div class="form-group">
        <div data-app>
            <div id="vue">
                <div class="mb-3">
                    {% if object.machine.category.name != '3D' %}
                        <v-row>
                            <v-col cols="6">
                                <time-picker init-time={{object.formatted_start_time}} input-name="start_time" label={% trans "Start" %}>
                                </time-picker>
                            </v-col>
                            <v-col cols="6">
                                <time-picker init-time={{object.formatted_end_time}} input-name="end_time" label={% trans "End" %}>
                                </time-picker>
                            </v-col>
                        </v-row>
                        {{ form.errors.start_time }}
                        {{ form.errors.end_time }}
                    {% else %}
                    <v-row>
                        <v-col cols="12">
                            <p>{% trans "You can start between " %} {{object.start|date:"H:i"}} {% trans " and " %} {{max_start_time|date:"H:i"}}</p>
                            <time-picker init-time={{object.formatted_start_time}} input-name="start_time" label={% trans "Time" %}>
                            </time-picker>
                            {{ form.errors.start_time }}
                        </v-col>
                    </v-row>

                    <v-row>
                        <v-col cols="12">
                            <h4> {% trans "End" %}</h4>
                            <p>
                            {% if next_object %}
                                {% trans "The 3D print in free until:" %} <br>
                                {{next_object.start|date:"l j F Y H:i"|capfirst}}
                            {% else %}
                                {% trans "There are no reservations for the next few days. Feel free to use it !" %}
                            {% endif %}</p>
                            <date-picker init-date={{object.formatted_end_date}} input-name="end_date" label={% trans "Date" %}>
                            </date-picker>
                            {{ form.errors.end_date}}
                            
                            <time-picker init-time={{object.formatted_end_time}} input-name="end_time" label={% trans "Time" %}>
                            </time-picker>
                            {{ form.errors.end_time }}
                        </v-col>
                    </v-row>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

    <hr>
    <div class="text-center">
        {% if request.user.profile.is_subscription_valid %}
            <h4>{{object.machine.premium_price|price_format}} / 30 min </h4>
        {% else %}
            <h4>{{object.machine.full_price|price_format}} / 30 min </h4>
        
            <small> {% trans "Benefit from half price prices<br> for 15 CHF / month" %}<br></small>
            <a class="btn btn-outline-primary my-2" href="/comment-ca-marche/#abonnement-demi-tarif"> {% trans "I take advantage of it" %}</a>        
        {% endif %}
    </div>
    <hr>
    {% include 'forms/base_submit_button.html' with submit_btn=_('Reserve')%}
</form>

{% endblock content_form %}

{% block js_footer %}
{% render_bundle 'vue' 'js' %}
{% endblock js_footer %}

fabcal/templates/fabcal/opening_calendar.html
{% load static interlab_tags i18n %}
{% load render_bundle from webpack_loader %}

{% block content %}

<div data-app>
    <div id="vue">
        <opening-calendar :backend="{{backend}}"></opening-calendar>
    </div>
</div>

{% endblock content %}

{% block js_footer %}
{% render_bundle 'vue' 'js' %}
{% endblock js_footer %}

fabcal/templates/fabcal/trainingslot_confirm_delete.html
{% extends "forms/base_forms.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}

{% block content_form_img %}
<i class="bi bi-calendar-x mb-5 img-form-logo mx-auto d-block text-red"></i>
{% endblock %}

{% block content_form %}
<div class="text-center">
    <h3> {% blocktrans with title=object.training.title  %} Do you want to delete the training {{title}}{% endblocktrans %}</h3>
    <p>{{format_info_datetime}}</p>
</div>
<form action={% url 'fabcal:trainingslot-delete' object.pk %} method="POST">
    {% csrf_token %}
    {% include "forms/base_submit_button.html" with submit_btn="Yes, I'm sure" %}
</form>

{% endblock content_form %}