accounts/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.views import PasswordResetConfirmView

app_name = 'accounts'

urlpatterns =[
    path('register/', views.CustomRegistrationView.as_view(), name='django_registration_register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='auth_password_reset_confirm'),
    path('profile/', views.AccountsView, name='profile'),
    path('profile/edit/', views.EditProfileView, name='edit-profile'),
    path('profile/delete/', views.DeleteProfileView, name='delete-profile'),
    path("profile/subscription-management/<int:organization_pk>/people/add/", views.OrganizationUserCreateView.as_view(), name="organization_user_add"),
    path('profile/subscription-management/', include('organizations.urls'), name='subscription-management'),
    path('invitations/token-error', views.token_error_view, name='invitations-token-error'),
    path('user-list', views.UserListView.as_view(template_name='accounts/user-list.html'), name='user-list'),
    path('user-list-filtered', views.UserListView.as_view(template_name='accounts/user-list-filtered.html'), name='user-list-filtered'),
    path('superuser-profile-edit/<int:pk>', views.SuperuserProfileEditView.as_view(), name='superuser-profile-edit')
]

api/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path('(?P<version>(v1))/opening/', views.OpeningSet.as_view()),
    re_path('(?P<version>(v1))/opening_slot/', views.OpeningSlotSet.as_view()),
    re_path('(?P<version>(v1))/machine_slot/', views.MachineSlotSet.as_view()),
    re_path('(?P<version>(v1))/training_slot/', views.TrainingSlotSet.as_view()),
    re_path('(?P<version>(v1))/custom_user/', views.CustomUserSet.as_view()),
    re_path('(?P<version>(v1))/subscription/', views.SubscriptionSet.as_view()),
    re_path('(?P<version>(v1))/profile/', views.ProfileSet.as_view()),
]

fabcal/urls.py
from django.urls import path
from . import views

app_name = 'fabcal'

urlpatterns = [
    path('openingslot/create/<str:start>/<str:end>/', views.OpeningSlotCreateView.as_view(), name='openingslot-create'),
    path('openingslot/update/<int:pk>/', views.OpeningSlotUpdateView.as_view(), name='openingslot-update'),
    path('openingslot/delete/<int:pk>/', views.OpeningSlotDeleteView.as_view(), name='openingslot-delete'),
    path('machineslot/update/<int:pk>/', views.MachineSlotUpdateView.as_view(), name='machineslot-update'),
    path('machineslot/delete/<int:pk>/', views.MachineSlotDeleteView.as_view(), name='machineslot-delete'),
    path('trainingslot/create/<str:start>/<str:end>/', views.TrainingSlotCreateView.as_view(), name='trainingslot-create'),
    path('trainingslot/update/<int:pk>/', views.TrainingSlotUpdateView.as_view(), name='trainingslot-update'),
    path('trainingslot/delete/<int:pk>/', views.TrainingSlotDeleteView.as_view(), name='trainingslot-delete'),
    path('trainingslot/register/create/<int:pk>/', views.TrainingSlotRegistrationCreateView.as_view(), name='trainingslot-register'),
    path('trainingslot/register/delete/<int:pk>/', views.TrainingSlotRegistrationDeleteView.as_view(), name='trainingslot-unregister'),
    path('eventslot/<int:pk>/', views.EventSlotDetailView.as_view(), name='eventslot-detail'),
    path('eventslot/create/<str:start>/<str:end>/', views.EventSlotCreateView.as_view(), name='eventslot-create'),
    path('eventslot/update/<int:pk>/', views.EventSlotUpdateView.as_view(), name='eventslot-update'),
    path('eventslot/delete/<int:pk>/', views.EventSlotDeleteView.as_view(), name='eventslot-delete'),
    path('eventslot/register/create/<int:pk>/', views.EventSlotRegistrationCreateView.as_view(), name='eventslot-register'),
    path('eventslot/register/delete/<int:pk>/', views.EventSlotRegistrationDeleteView.as_view(), name='eventslot-unregister'),
    path('download-ics-file/<str:summary>/<str:start>/<str:end>/', views.downloadIcsFileView.as_view(), name='download-ics-file'),
    path('machine/reservation/future/', views.MachineFutureReservationListView.as_view(), name='machine-reservation-future'),
    path('machine/reservation/past/', views.MachinePastReservationListView.as_view(), name='machine-reservation-past')
]

interlab/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from . import views

from organizations.backends import invitation_backend

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('machines/', include('machines.urls')),
    path('invitations/', include(invitation_backend().get_urls())),
    path('fabcal/', include('fabcal.urls')),
    path('share/', include('share.urls')),
    path('payments/', include('payments.urls')),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path('error-500/', views.error_500, name='error-500'),
    path("", include("newsletter.urls")),
    path("", include("cms.urls")),
    prefix_default_language=False
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += i18n_patterns(
       path(r'^__debug__/', include(debug_toolbar.urls)),
       prefix_default_language=False
    )

machines/urls.py
from django.urls import path

from . import views

app_name = 'machines'

urlpatterns = [
    path('training/<int:pk>/', views.training_show, name='training-detail'),
    path('trainings/<int:pk>/validation/', views.TrainingValidationView.as_view(), name='training-validation'),
    path('trainings/<int:pk>/waiting-list/', views.training_waiting_list, name='training-waiting-list'),
    path('machines/<int:pk>/show', views.MachineShowView.as_view(), name='machines-show'),
    path('machine/<int:pk>/slot', views.MachineSlotView.as_view(), name='machines-slot')
]

profile/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('', views.profile, name='profile'),
]
    

accounts/views.py
import datetime
from itertools import chain
from operator import attrgetter
import dateparser

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.sessions.models import Session
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Q, OuterRef, Exists
from django.http import HttpResponse
from django.template import loader
from django.utils.translation import gettext as _
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic.base import TemplateView


from fabcal.models import EventSlot, OpeningSlot, TrainingSlot, MachineSlot, RegistrationEventSlot
from machines.models import TrainingValidation

from .forms import EditUserForm, EditProfileForm, CustomOrganizationUserAddForm, CustomRegistrationForm, CustomAuthenticationForm, SuperuserProfileEditForm
from .models import Profile

from organizations.views.base import BaseOrganizationUserCreate
from organizations.views.base import BaseOrganizationUserDelete
from organizations.views.mixins import OwnerRequiredMixin

from django_registration.backends.activation.views import RegistrationView
from django_registration import signals

from newsletter.views import register_email, get_contact, update_contact
from interlab.views import CustomFormView

class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm

class CustomRegistrationView(RegistrationView):
    template_name = 'registration/registration_form.html'
    form_class = CustomRegistrationForm

    def register(self, form):
        new_user = self.create_inactive_user(form)

        # Add user to newsletter list
        if form.cleaned_data['newsletter']: 
            register_email(form.cleaned_data['email'])
        
        signals.user_registered.send(
            sender=self.__class__, user=new_user, request=self.request
        )
        return new_user

@login_required
def AccountsView(request):
    user = request.user
    template = loader.get_template('accounts/profile.html')

    today = datetime.date.today()

    # Subquery to check if the user has registrations for the event slot
    registration_event_slot = RegistrationEventSlot.objects.filter(
        event_slot=OuterRef('pk'),
        event_slot__end__gte=today,
        user=request.user
    )

    context = {
        'page_title': "My account",
        'user': user,
        'slots': sorted(chain(
            TrainingSlot.objects.filter(user=request.user, end__gte=datetime.date.today()),
            TrainingSlot.objects.filter(registrations=request.user, end__gte=datetime.date.today()),
            EventSlot.objects.filter(user=request.user, end__gte=datetime.date.today()),
            EventSlot.objects.filter(Exists(registration_event_slot)),
            OpeningSlot.objects.filter(user=request.user, end__gte=datetime.date.today()), 
            MachineSlot.objects.filter(user=request.user, end__gte=datetime.date.today()),
        ),
        key=attrgetter('start')
        )
    }

    (profile, _) = Profile.objects.get_or_create(user=user)
    if profile.subscription is not None:
        context['subscription'] = profile.subscription
        context['subscription_category']=profile.subscription.subscription_category_id
        
    return HttpResponse(template.render(context, request))

@login_required
def EditProfileView(request):
    template = 'accounts/profile_edit.html'

    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            # Check if profile has newsletter
            contacts = get_contact()
            mail_list = [contact['email'] for contact in contacts['data']['data']]
            if 'email' in user_form.changed_data:
                old_email = user_form.initial['email']
                if old_email in mail_list:
                    user_id = next((contact['id'] for contact in contacts['data']['data'] if contact['email'] == old_email), None)
                    if user_id is not None:
                        new_email = user_form.cleaned_data['email']
                        update_contact(user_id, new_email)
                        messages.success(request, _("Your newsletter registration has been updated successfully with the email address: ") + new_email)

            user_form.save()
            profile_form.save()

            messages.success(request, _("Your profile has been updated successfully"))
            return redirect('accounts:profile')
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)

    context = {
        "edit_user_form": user_form,
        "edit_profile_form": profile_form
    }

    return render(request, template, context)

@login_required
def DeleteProfileView(request):
    template = 'accounts/profile_delete.html'
    context = {
        'page_title': "Delete my profile" 
    }
    if request.method == 'POST':
        user = request.user
        user.is_active = False
        user.save()
        messages.success(request, _("Your account has been successfully deleted") )
        [s.delete() for s in Session.objects.all() if s.get_decoded().get('_auth_user_id') == user.id]
        return redirect('/')

    return render(request, template, context)

class OrganizationUserDeleteView(OwnerRequiredMixin, LoginRequiredMixin, BaseOrganizationUserDelete):
    def post(self, request, *args, **kwargs):

        # Remove user from organization
        self.organization.remove_user(self.organization_user.user)

        # Remove subscription of the user
        try:
            profile = Profile.objects.get(user_id=self.organization_user.user_id)
            profile.subscription = None
            profile.save()
        except Profile.DoesNotExist:
            pass
        
        if self.organization_user.user.first_name:
            messages.success(request, self.organization_user.user.first_name + self.organization_user.user.last_name + _(" has been removed successfully from the team.") )
        else:
            messages.success(request, self.organization_user.user.email + _(" has been removed successfully from the team.") )
        return redirect('organization_detail', organization_pk=request.user.organizations_organization.first().pk)

class OrganizationUserCreateView(OwnerRequiredMixin, LoginRequiredMixin, BaseOrganizationUserCreate):
    form_class = CustomOrganizationUserAddForm

def token_error_view(request): 
    template = 'organizations/invitations_token_error.html'
    return render(request, template) 

class UserListView(LoginRequiredMixin, TemplateView):
    number_of_item = 10

    def get(self, *args, **kwargs):
        if not self.request.user.groups.filter(name = 'superuser').exists():
            raise PermissionDenied
        else:
            template = self.template_name
            context = self.get_context_data()
            return render(self.request, template, context)  

    def post(self, *args, **kwargs):
        template = self.template_name
        context = self.get_context_data()
        return render(self.request, template, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = self.find_user(self.request.POST.get('search'))
        users = self.get_page_obj(self.request, users, self.number_of_item)
        context['users'] = users
        return context

    def get_page_obj(self, request, list_of_objects, number_of_item):
        paginator = Paginator(list_of_objects, number_of_item)
        page_number = request.GET.get('page')
        return paginator.get_page(page_number)

    def find_user(self, query):
        qs = get_user_model().objects.all()
        if query:
            for term in query.split():
                qs = qs.filter( 
                    Q(first_name__icontains = term) | 
                    Q(last_name__icontains = term) |
                    Q(email__icontains = term)
                    )
        return qs

class SuperuserProfileEditView(LoginRequiredMixin, CustomFormView):
    template_name = 'accounts/superuser-profile-edit.html'
    form_class = SuperuserProfileEditForm

    def get_success_url(self):
        return reverse('accounts:user-list')

    def get_initial(self):
        initial = super().get_initial()
        self.user = get_user_model().objects.get(pk=self.kwargs['pk'])
        if self.user.profile is not None \
            and self.user.profile.subscription is not None \
            and self.user.profile.subscription.subscription_category is not None:
            initial['subscription_category'] = self.user.profile.subscription.subscription_category
            initial['start'] = self.user.profile.subscription.start
            initial['end'] = self.user.profile.subscription.end

        if self.user.profile is not None:
             initial['training'] = [t.training.pk for t in TrainingValidation.objects.filter(profile=self.user.profile)]

        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.user

        if context['form'].initial.get('subscription_category', None) is not None:
            context['start'] = context['form'].initial['start']
            context['end'] = context['form'].initial['end']
        else:
            today = datetime.datetime.today()
            context['start'] = today
            context['end'] = today + datetime.timedelta(days=365)
        return context
    
    def form_invalide(self):
        pass

accounts/templates/accounts/avatar.html
<div class="rounded-circle mx-auto" style="background-color:#0b1783;; height:60px; width:60px;">
    <div class="justify-content-center d-flex align-items-center h-100" style="color:white;">
        {{user.first_name|capfirst|make_list|first}} {{user.last_name|capfirst|make_list|first}}
    </div>
    
    {% if user.profile.is_subscription_valid %}
    <i class="bi bi-star-fill text-red position-relative icon-subscription icon-shadow"></i>
    {% endif %}
</div>

accounts/templates/accounts/nav.html
{% load i18n interlab_tags %}

{% if request.user.organizations_organization.first %}
{% load org_tags %}
{% if request.user.organizations_organization.first|is_owner:user %}
<a class="px-0 text-blue" href="{% url 'organization_detail' request.user.organizations_organization.first.pk %}">
    <div class="row">
        <div class="col-12 py-0">
            <div class="row fs-4">
                <div class="col-10 py-0">
                    {% trans "My subscription" %}
                </div>
            </div>
            <div class="row">
                <div class="col-12 pt-0">
                    <p>{% trans "Manage subscription members" %}</p>
                </div>
            </div>

        </div>
    </div>
</a>
<hr>
{% endif %}
{% endif %}


<a class="px-0 text-blue" href="{% url 'accounts:edit-profile' %}">
    <div class="row">
        <div class="col-12 py-0">
            <div class="row fs-4">
                <div class="col-10 py-0">
                    <i class="bi bi-person-fill pe-2"></i> {% trans "My profile" %}
                </div>
            </div>
            <div class="row">
                <div class="col-12 pt-0">
                    <p>{% trans "name"|capfirst %}, {% trans "email" %}, {% trans "password" %},
                        {% trans "delete account" %}</p>
                </div>
            </div>
        </div>
    </div>
</a>
<hr>
<a class="px-0 text-blue" href="/accounts/logout">
    <div class="row">
        <div class="col-12 pt-0">
            <div class="row fs-4">
                <div class="col-10">
                    {% trans "Logout" %}
                </div>
                <div class="col-2 text-end">
                    <i class="bi bi-box-arrow-right pe-2"></i> 
                </div>
            </div>
        </div>
    </div>
</a>
{% if request.user|has_group:"superuser" %}
<hr class="text-red">
<a class="px-0" href="{% url 'accounts:user-list' %}">
    <div class="row">
        <div class="col-12 py-0">
            <div class="row fs-4">
                <div class="col-10 py-0">
                    <i class="bi bi-people-fill pe-2"></i> {% trans "Users" %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-12 pt-0">
                    <p>{% trans "training validation"|capfirst %}, {% trans "subscription" %}</p>
                </div>
            </div>
        </div>
    </div>
</a>
<hr class="text-red">
<a class="px-0" href="{% url 'fabcal:machine-reservation-future' %}">
    <div class="row">
        <div class="col-12 py-0">
            <div class="row fs-4">
                <div class="col-10 py-0">
                    <i class="bi bi-calendar-week-fill pe-2"></i> {% trans "Reservations" %}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-12 pt-0">
                    <p>{% trans "Future and past reservations"%}</p>
                </div>
            </div>
        </div>
    </div>
</a>
{% endif %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load i18n org_tags interlab_tags %}

{% block content %}
<div class="row g-5">
    <div class="col-12 col-lg-4 py-5 navbar-profile">
        <div class="card">
            <div class="card-body p-4">
                {% include 'accounts/user-summary.html' %}
                <div class="d-none d-lg-block">
                    <hr>
                    {% include 'accounts/nav.html' %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-lg-8 py-5">
        <h1>{%trans "My future activities in Fablab" %}</h1>
        <div class="row">
            {% for slot in slots %}
            <div class="col-12">
                {% if slot|get_type == 'TrainingSlot'%}
                {% include 'accounts/profile_trainingslot.html' %}
                {% endif %}

                {% if slot|get_type == 'EventSlot'%}
                {% include 'accounts/profile_eventslot.html' %}
                {% endif %}

                {% if slot|get_type == 'OpeningSlot'%}
                {% include 'accounts/profile_openingslot.html' %}
                {% endif %}

                {% if slot|get_type == 'MachineSlot'%}
                {% include 'accounts/profile_machineslot.html' %}
                {% endif %}
            </div>
            {% empty %}
            <p>{%trans "Nothing planned at the moment..." %}</p>
            <div class="row text-center align-items-center">
                <div class="col">
                    <a class="btn btn-outline-primary m-2" href="/trainings/">
                        <i class="bi bi-mortarboard-fill pe-2"></i> {% trans "Register a training" %}
                    </a>
                </div>
                <div class="col">
                    <a class="btn btn-outline-primary m-2" href="/machines/">
                        <i class="bi bi-tools pe-2"></i> {% trans "Book a machine" %}
                    </a>
                </div>
                {% if request.user|has_group:"superuser" %}
                <div class="col">
                    <a class="btn btn-primary m-2" href="/schedule/">
                        <i class="bi bi-door-open-fill pe-2"></i> {% trans "Add an opening" %}
                    </a>
                </div>


                {% elif slot|get_type == 'EventSlot' %}
                <div class="row">
                    <div class="col-8">
                <h5>
                    {% trans "Event" %}
                    {{slot.event.title}}
                </h5>
                <p class='badge align-middle'
                    style="color:{{slot.opening_slot.opening.color}};background-color:{{slot.opening_slot.opening.background_color}}">
                    {{slot.opening_slot.opening.title}} - {{slot.opening_slot.user.first_name}}
                </p>
            </div>

                {% elif slot|get_type == 'EventSlot' %}
                <a href="{% url 'fabcal:eventslot-detail' slot.pk %}">
                    <i class="bi bi-pencil-square text-blue fs-1"></i>
                </a>
            </div>
        </div>
        {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-12 d-lg-none py-5">
        <hr>
        {% include 'accounts/nav.html' %}
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/profile_machineslot_delete_btn.html
{% load i18n %}

{% if not slot.is_editable %}
<button type="button" class="btn btn-link btn-outline-primary" data-bs-toggle="tooltip"
    data-bs-placement="top"
    title="{% trans 'It is not possible to cancel the reservation 24h before the begining of the slot. Please contact us.' %}">
    <i class="bi bi-trash3"></i>
</button>
{% else %}
<a class="btn btn-link btn-outline-primary"
    href="{% url 'fabcal:machineslot-delete' slot.pk %}">
    <i class="bi bi-trash3"></i>
</a>
{% endif %}

accounts/templates/accounts/profile_openingslot.html
{% load i18n %}


<!-- Mobile -->
<div class="d-md-none">
    <div class="card">
        <div class="position-relative">
            <img class="img-fluid rounded-top" src={{slot.opening.photo.url}}>
            <p class='badge position-absolute top-0 start-0 m-2'
                style="color:{{slot.opening.color}};background-color:{{slot.opening.background_color}}">
                {{slot.opening.title}}
            </p>

            <div class="position-absolute top-0 end-0 p-2">
                {%include 'accounts/profile_openingslot_delete_btn.html'%}
            </div>
        </div>

        <div class="card-body">
            <h4 class="card-title">{% trans "Opening" %}</h4>
            {%include 'accounts/profile_slot_datetime.html'%}

            {%include 'accounts/profile_openingslot_reservation_list.html'%}

            <div class="row">
                <div class="col text-center">
                    <a href="{% url 'fabcal:openingslot-update' slot.pk %}"
                        class="btn btn-primary"> <i class="bi bi-pencil pe-2"></i> {% trans "Edit my opening" %}</a>
                </div>
            </div>

        </div>
    </div>
</div>

<!-- Desktop -->
<div class="d-none d-md-block">
    <hr>
    <div class="row">
        <div class="col-3 py-0">
            <img class="img-fluid rounded" src={{slot.opening.photo.url}}>
        </div>
        <div class="col-9 py-0">
            <div class="row">
                <div class="col-8 py-auto">
                    <span class="h4 align-middle d-inline pe-2">{%trans "Opening" %}</span>
                    <span class='badge d-inline align-middle'
                        style="color:{{slot.opening.color}};background-color:{{slot.opening.background_color}}">
                        {{slot.opening.title}}
                    </span>
                    {%include 'accounts/profile_slot_datetime.html'%}
                </div>
                <div class="col-4 text-end py-0">
                    <a class="btn btn-link btn-outline-primary" href="{% url 'fabcal:openingslot-update' slot.pk %}">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    {%include 'accounts/profile_openingslot_delete_btn.html'%}
                </div>
            </div>

            {%include 'accounts/profile_openingslot_reservation_list.html'%}

        </div>
    </div>
</div>

accounts/templates/accounts/profile_openingslot_delete_btn.html
{% load i18n %}

{% if not slot.is_editable %}
<button type="button" class="btn btn-link btn-outline-primary" data-bs-toggle="tooltip"
    data-bs-placement="top" title="{% trans 'You have reservations!' %}">
    <i class="bi bi-trash3"></i>
</button>
{% else %}
<a class="btn btn-link btn-outline-primary" href="{% url 'fabcal:openingslot-delete' slot.pk %}">
    <i class="bi bi-trash3"></i>
</a>
{% endif %}

accounts/templates/accounts/profile_openingslot_reservation_list.html
{% load i18n %}

<div class="row">
    <div class="col">
        <h5>{% trans "Reservations" %}</h5>
        {% for reservation in slot.get_reservation_list %}
        <a class="text-blue" href="{% url 'accounts:superuser-profile-edit' reservation.user.pk %}">
            <div class="row">
                <div class="col-3 col-md-2">
                    {%include 'accounts/avatar.html' with user=reservation.user%}
                </div>
                <div class="col-9 my-auto">
                    {{reservation.user.first_name}} {{reservation.user.last_name}} <br>
                    {{reservation.start|date:"H:i"}} - {{reservation.end|date:"H:i"}}:
                    {{reservation.machine.title}} 
                </div>
            </div>
        </a>
        {% empty %}
        {% trans "No reservations for the moment" %}
        {% endfor %}
    </div>
</div>

accounts/templates/accounts/profile_slot_datetime.html
<p>{{slot.start|date:"d F"}} - {{slot.start|date:"H:i"}} à {{slot.end|date:"H:i"}}</p>

accounts/templates/accounts/profile_trainingslot.html
{% load i18n %}


<!-- Mobile -->
<div class="d-md-none">
    <div class="card">
        <div class="position-relative">
            <a href="{% url 'machines:training-detail' slot.pk %}">
                <img class="img-fluid rounded-top" src={{slot.training.photo.url}}>
            </a>
            {% if slot.opening_slot %}
            <p class='badge position-absolute top-0 start-0 m-2'
                style="color:{{slot.opening_slot.opening.color}};background-color:{{slot.opening_slot.opening.background_color}}">
                {{slot.opening_slot.opening.title}}
            </p>
            {% endif %}

            <div class="position-absolute top-0 end-0 p-2">
                {%include 'accounts/profile_trainingslot_delete_btn.html'%}
            </div>
        </div>

        <div class="card-body">
            <h4 class="card-title">{% trans "Training" %}</h4>
            <h5 class="card-title">{{slot.training.title}}</h5>
            {%include 'accounts/profile_slot_datetime.html'%}

            {% if request.user == slot.user %}
            {%include 'accounts/profile_slot_registration_list.html'%}

            <div class="row">
                <div class="col text-center">
                    <a class="btn btn-outline-primary my-4" href="{% url 'machines:training-validation' slot.pk %}">
                        <i class="bi bi-card-checklist pe-2"></i> {% trans "Validate trainings" %}
                    </a>
                    <a href="{% url 'fabcal:trainingslot-update' slot.pk %}" class="btn btn-primary"> <i
                            class="bi bi-pencil pe-2"></i> {% trans "Edit my training" %}</a>
                </div>
            </div>

            {% endif %}

        </div>
    </div>
</div>

<!-- Desktop -->
<div class="d-none d-md-block">
    <hr>
    <div class="row">
        <div class="col-3 py-0">
            <a href="{% url 'machines:training-detail' slot.pk %}">
                <img class="img-fluid rounded" src={{slot.training.photo.url}}>
            </a>
        </div>
        <div class="col-9 py-0">
            <div class="row">
                <div class="col-8 py-auto">
                    <span class="h4 align-middle d-inline pe-2">{%trans "Training" %}</span>
                    {% if slot.opening_slot %}
                    <span class='badge d-inline align-middle'
                        style="color:{{slot.opening_slot.opening.color}};background-color:{{slot.opening_slot.opening.background_color}}">
                        {{slot.opening_slot.opening.title}}
                    </span>
                    <h5 class="card-title">{{slot.training.title}}</h5>
                    {% endif %}

                    {%include 'accounts/profile_slot_datetime.html'%}
                </div>
                <div class="col-4 text-end py-0">
                    <a class="btn btn-link btn-outline-primary" href="{% url 'fabcal:trainingslot-update' slot.pk %}">
                        <i class="bi bi-pencil-square"></i>
                    </a>
                    {%include 'accounts/profile_trainingslot_delete_btn.html'%}
                </div>
            </div>
            {%include 'accounts/profile_slot_registration_list.html'%}
            <div class="row">
                <div class="col text-center">
                    <a class="btn btn-outline-primary" href="{% url 'machines:training-validation' slot.pk %}">
                        <i class="bi bi-card-checklist"></i> {% trans "Validate trainings" %}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>