accounts/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth.views import PasswordResetConfirmView

app_name = 'accounts'

urlpatterns =[
    path('register/', views.CustomRegistrationView.as_view(), name='django_registration_register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='auth_password_reset_confirm'),
    path('profile/', views.AccountsView, name='profile'),
    path('profile/edit/', views.EditProfileView, name='edit-profile'),
    path('profile/delete/', views.DeleteProfileView, name='delete-profile'),
    path("profile/subscription-management/<int:organization_pk>/people/add/", views.OrganizationUserCreateView.as_view(), name="organization_user_add"),
    path('profile/subscription-management/', include('organizations.urls'), name='subscription-management'),
    path('invitations/token-error', views.token_error_view, name='invitations-token-error'),
    path('user-list', views.UserListView.as_view(template_name='accounts/user-list.html'), name='user-list'),
    path('user-list-filtered', views.UserListView.as_view(template_name='accounts/user-list-filtered.html'), name='user-list-filtered'),
    path('superuser-profile-edit/<int:pk>', views.SuperuserProfileEditView.as_view(), name='superuser-profile-edit')
]

api/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path('(?P<version>(v1))/opening/', views.OpeningSet.as_view()),
    re_path('(?P<version>(v1))/opening_slot/', views.OpeningSlotSet.as_view()),
    re_path('(?P<version>(v1))/machine_slot/', views.MachineSlotSet.as_view()),
    re_path('(?P<version>(v1))/training_slot/', views.TrainingSlotSet.as_view()),
    re_path('(?P<version>(v1))/custom_user/', views.CustomUserSet.as_view()),
    re_path('(?P<version>(v1))/subscription/', views.SubscriptionSet.as_view()),
    re_path('(?P<version>(v1))/profile/', views.ProfileSet.as_view()),
]

fabcal/urls.py
from django.urls import path
from . import views

app_name = 'fabcal'

urlpatterns = [
    path('openingslot/create/<str:start>/<str:end>/', views.OpeningSlotCreateView.as_view(), name='openingslot-create'),
    path('openingslot/update/<int:pk>/', views.OpeningSlotUpdateView.as_view(), name='openingslot-update'),
    path('openingslot/delete/<int:pk>/', views.OpeningSlotDeleteView.as_view(), name='openingslot-delete'),
    path('machineslot/update/<int:pk>/', views.MachineSlotUpdateView.as_view(), name='machineslot-update'),
    path('machineslot/delete/<int:pk>/', views.MachineSlotDeleteView.as_view(), name='machineslot-delete'),
    path('trainingslot/create/<str:start>/<str:end>/', views.TrainingSlotCreateView.as_view(), name='trainingslot-create'),
    path('trainingslot/update/<int:pk>/', views.TrainingSlotUpdateView.as_view(), name='trainingslot-update'),
    path('trainingslot/delete/<int:pk>/', views.TrainingSlotDeleteView.as_view(), name='trainingslot-delete'),
    path('trainingslot/register/create/<int:pk>/', views.TrainingSlotRegistrationCreateView.as_view(), name='trainingslot-register'),
    path('trainingslot/register/delete/<int:pk>/', views.TrainingSlotRegistrationDeleteView.as_view(), name='trainingslot-unregister'),
    path('eventslot/<int:pk>/', views.EventSlotDetailView.as_view(), name='eventslot-detail'),
    path('eventslot/create/<str:start>/<str:end>/', views.EventSlotCreateView.as_view(), name='eventslot-create'),
    path('eventslot/update/<int:pk>/', views.EventSlotUpdateView.as_view(), name='eventslot-update'),
    path('eventslot/delete/<int:pk>/', views.EventSlotDeleteView.as_view(), name='eventslot-delete'),
    path('eventslot/register/create/<int:pk>/', views.EventSlotRegistrationCreateView.as_view(), name='eventslot-register'),
    path('eventslot/register/delete/<int:pk>/', views.EventSlotRegistrationDeleteView.as_view(), name='eventslot-unregister'),
    path('download-ics-file/<str:summary>/<str:start>/<str:end>/', views.downloadIcsFileView.as_view(), name='download-ics-file'),
    path('machine/reservation/future/', views.MachineFutureReservationListView.as_view(), name='machine-reservation-future'),
    path('machine/reservation/past/', views.MachinePastReservationListView.as_view(), name='machine-reservation-past')
]

interlab/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from . import views

from organizations.backends import invitation_backend

admin.autodiscover()

urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls')),
    path('machines/', include('machines.urls')),
    path('invitations/', include(invitation_backend().get_urls())),
    path('fabcal/', include('fabcal.urls')),
    path('share/', include('share.urls')),
    path('payments/', include('payments.urls')),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    path('error-500/', views.error_500, name='error-500'),
    path("", include("newsletter.urls")),
    path("", include("cms.urls")),
    prefix_default_language=False
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += i18n_patterns(
       path(r'^__debug__/', include(debug_toolbar.urls)),
       prefix_default_language=False
    )

machines/urls.py
from django.urls import path

from . import views

app_name = 'machines'

urlpatterns = [
    path('training/<int:pk>/', views.training_show, name='training-detail'),
    path('trainings/<int:pk>/validation/', views.TrainingValidationView.as_view(), name='training-validation'),
    path('trainings/<int:pk>/waiting-list/', views.training_waiting_list, name='training-waiting-list'),
    path('machines/<int:pk>/show', views.MachineShowView.as_view(), name='machines-show'),
    path('machine/<int:pk>/slot', views.MachineSlotView.as_view(), name='machines-slot')
]

machines/forms.py
from django import forms
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from machines.models import TrainingValidation
from accounts.models import Profile

class TrainingValidationForm(forms.Form):
    validations = forms.BooleanField(required=False)

    def add_new_training_validation(self, view):
         # old:0 -> new:1
        for i in view.new:
            if i not in view.old:
                profile = get_object_or_404(Profile, pk=i)
                TrainingValidation.objects.update_or_create(
                        training = view.training,
                        profile =  profile
                    )
                message = "You successfully validate the training %(title)s for user %(first_name)s %(last_name)s"
                context = {
                        'title': view.training.title, 
                        'first_name': profile.user.first_name, 
                        'last_name': profile.user.last_name
                        }

                messages.success(view.request, _(message) % context)
                
    def remove_training_validation(self, view):
        # old:1 -> new:0
        for i in view.old:
            if i not in view.new:
                profile = get_object_or_404(Profile, pk=i)
                TrainingValidation.objects.get(
                        training = view.training,
                        profile =  profile
                ).delete()
                message = "You successfully remove the training %(title)s for user %(first_name)s %(last_name)s"
                context = {
                        'title': view.training.title, 
                        'first_name': profile.user.first_name, 
                        'last_name': profile.user.last_name
                        }

                messages.success(view.request, _(message) % context)

machines/views.py
import datetime


from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import gettext as _
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Training, ToolTraining, TrainingValidation, TrainingNotification, Machine
from .forms import TrainingValidationForm

from fabcal.models import TrainingSlot, MachineSlot

# TODO change to DetailView
def training_show(request, pk):
    training = get_object_or_404(Training, pk=pk)

    if request.user.is_authenticated:
        notification = TrainingNotification.objects.filter(profile=request.user.profile, training=training).exists()
        if request.method == 'POST':
            if notification:
                # user has already the notification and want to unsuscribe
                TrainingNotification.objects.get(profile=request.user.profile, training=training).delete()
                messages.success(request, _("Oh no! you unsubsribe from notification"))
            else:
                TrainingNotification.objects.update_or_create(profile = request.user.profile, training=training)
                messages.success(request, _("Thanks for interest, we will contact you as soon as possible"))
            
            #update notification variable 
            notification = TrainingNotification.objects.filter(profile__user=request.user, training=training).exists()

    else: 
        notification = False

    context = {
        'training': training,
        'training_slots': TrainingSlot.objects.filter(training__pk = pk, start__gte=datetime.datetime.now()).order_by('start'),
        'machines': training.machines_list,
        'tools': ToolTraining.objects.filter(training__pk=pk).order_by('sort'),
        'notification': notification,
        'interested_user_count': TrainingNotification.objects.filter(training=training).count()
        }

    return render(request, 'trainings/show.html', context)


class TrainingValidationView(LoginRequiredMixin, FormView):
    template_name = 'trainings/training_validation.html'
    form_class = TrainingValidationForm
    success_url = "/" # TODO redirect to training show view

    def get_context_data(self, **kwargs):
        training_slot = get_object_or_404(TrainingSlot, pk=self.kwargs['pk'])
        registrations = training_slot.registrations.all()
        graduates = [
            i.profile
            for i in TrainingValidation.objects.filter(
                training__pk=training_slot.training.pk
            )
            if i.profile.user in registrations
        ]

        context = {
            'registrations': registrations,
            'graduates': graduates,
            'training': training_slot.training,
            'training_slot': training_slot
        }

        return context

    def form_valid(self, form, **kwargs):
        context = self.get_context_data(**kwargs)
        self.old = [graduate.pk for graduate in context['graduates']] # list of initial Profile pk checked
        self.new = [int(i) for i in self.request.POST.getlist('validations')] # list of Profile pk checked
        self.training = context['training']

        form.add_new_training_validation(self)
        form.remove_training_validation(self)

        return redirect('/')

@login_required
def training_waiting_list(request, pk):
    context = {
        'training_notifications': TrainingNotification.objects.filter(training__pk=pk).all().order_by('modified_date'),
        'training': get_object_or_404(Training, pk=pk)
    }
    return render(request, 'trainings/waiting_list.html', context)

class MachineShowView(DetailView):
    template_name = 'machines/show.html'
    model = Machine

    def get_context_data(self, **kwargs):
        context = super(MachineShowView, self).get_context_data(**kwargs)
        
        next_opening_slots = []
        for i in MachineSlot.objects.filter(machine=context['machine'], end__gt=datetime.datetime.now()).order_by('start'):
            if i.opening_slot not in next_opening_slots:
                next_opening_slots.append(i.opening_slot)

        context['next_opening_slots'] = next_opening_slots
        context['FABCAL_MINIMUM_RESERVATION_TIME'] = settings.FABCAL_MINIMUM_RESERVATION_TIME
        context['FABCAL_RESERVATION_INCREMENT_TIME'] = settings.FABCAL_RESERVATION_INCREMENT_TIME
        return context

class MachineSlotView(MachineShowView):
    template_name = 'machines/mobile_slots.html'

machines/templates/trainings/card.html
{% load i18n %}
<div class="col-6 col-lg-4">
    <a href="{% url 'machines:training-detail' obj.pk %}">
        <div class="card card-border-red">
            <img class="card-img" src="{{obj.photo.url}}" alt="{{obj.title}}">
            <div class="card-img-overlay h-100 d-flex flex-column justify-content-end p-0">
                <p class="card-title card-title-overlay mb-0 p-2">{{obj.title}}</p>
            </div>
        </div>
    </a>
</div>

machines/templates/trainings/info.html
{% load i18n training_extras %}

<div class="row">

    <div class="col-6 col-sm-4">
        <div class="row">
            <div class="col-4 text-end pe-0">
                <h4><i class="bi bi-cash"></i></h4>
            </div>
            <div class="col-8 ">
                <h4>{% trans "Price" %}</h4>
                <p>{{training.full_price|price_format}}</p>
            </div>
        </div>
    </div>

    <div class="col-6 col-sm-4">
        <div class="row">
            <div class="col-4 text-end pe-0">
                <h4><i class="bi bi-clock"></i></h4>
            </div>
            <div class="col-8 ">
                <h4>{% trans "Duration" %}</h4>
                <p>{{training.duration|duration_format}}</p>
            </div>
        </div>
    </div>

    <div class="col-6 col-sm-4">
        <div class="row">
            <div class="col-4 text-end pe-0">
                {% if training.level == 'BEG' %}
                    <h4><i class="bi bi-bar-chart"></i></h4>
                {% else %}
                    <h4><i class="bi bi-bar-chart-fill"></i></h4>
                {% endif %}
            </div>
            <div class="col-8 ">
                <h4>{% trans "Level" %}</h4>
                <p>{{training.level|level_format}}</p>
            </div>
        </div>
    </div>
</div>
{% if training.includ_free_machine_voucher %}
<div class="row border border-primary border-2 rounded">
    <div class="col-2 col-sm-1">
        <h4><i class="bi bi-arrow-repeat"></i></h4>
    </div>
    <div class="col-10 col-sm-11">
        {% trans "The price includes the training and a 1 hour machine voucher valid during 2 month after the training to start your project" %}
    </div>
</div>
{% endif %}

machines/templates/trainings/list.html
{% load i18n static interlab_tags %}

{% block content %}
<div class="row">
    {% for obj in trainings %}
        {%include 'trainings/card.html'%}
    {% empty %}
        <p>{% trans "Sadly, no training founded." %}</p>
    {% endfor %}
</div>
{% endblock %}

machines/templates/trainings/show.html
{% extends "base.html" %}
{% load i18n training_extras %}

{% block title %}{{block.super}} - {{training.title}} {% endblock %}

{% block content %}

<div class="row">
    <h2 class="text-red">{{training}}</h2>
    <div class="d-md-none"> {%include 'trainings/show_img.html'%} </div>
</div>
<div class="row gx-5">
    <div class="col-md-6">
        <h3>{{ training.header | safe }}</h3>
        <div class="d-md-none d-md-block">
            {% include 'trainings/info.html' %}
            {% include 'trainings/show_next_trainings.html' %}
            {% include 'trainings/show_waiting_list.html' %}
            <hr>
            <h3> {% trans "Description" %} </h3>
        </div>

        <p>{{training.desc}}</p>

        <div class="row mb-4">
            <div class="col">
                {% include 'faq/show.html' with faqs=training.faq_list %}
            </div>
        </div>

        <!-- TODO: Section machines associées:
            - récupérer avec une query les machines qui ont la même machine_category que le training
            - réutiliser l'affichage utilisé pour la liste de formations
            - implémenter un scroll horizontal (je sais pas comment faire, mais ça devrait être faisable en CSS)
        -->

        <div class="row mb-4">
            <h3> {% trans "Machines" %}</h3>

            {% if machines %}
            {% for machine in machines %}
                <div class="col-6 d-flex align-items-stretch text-center">
                    {% include 'machines/card.html' %}
                </div>
            {% endfor %}
            {% else %}
            <div class="col">
                <p>{% trans "Sadly, no machine currently available." %}</p>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="col-md-6">
        <div class="d-none d-md-block">{%include 'trainings/show_img.html'%}</div>
        <div class="d-none d-md-block">
            {% include 'trainings/info.html' %}
            {% include 'trainings/show_next_trainings.html' %}
            {% include 'trainings/show_waiting_list.html' %}
        </div>
    </div>
</div>

<div class="row">
    <h3> {% trans "Support and tools" %} </h3>
    {% for tool in tools %}
        <div class="text-center col-6 col-sm-6 col-md-4 col-lg-3 col-xl-2">
            {% include 'cards/show.html' with card=tool.card %}
        </div>
    {% endfor %}
</div>
{% endblock %}

machines/templates/trainings/show_img.html
<img class="img img-fluid rounded" src="{{training.photo.url}}">

machines/templates/trainings/show_next_trainings.html
{% load i18n interlab_tags %}

<div class="row pt-4">
<h3> {% trans "Next Trainings" %} </h3>
</div>
{% if training_slots %}
<div class="row mb-4">
    {% for training_slot in training_slots %}
    <hr>
    <div class="col-8">
        {{training_slot.start|date:"l j F Y"|capfirst}} {% trans " from " %} {{training_slot.start|date:"H:i"}}
        {% trans "to" %} {{training_slot.end|date:"H:i"}} <br>
        {% if training_slot.available_registration > 0  %}
        <small class"fs-6">
            {% if request.user in training_slot.registrations.all %}
                {% trans "You are already registered !" %}
            {% else %}
                {% blocktrans with available_registration=training_slot.available_registration %}still {{available_registration}} places available !{% endblocktrans %}
            {% endif %}
        </small>
        {% elif training_slot.available_registration == 0 %}
        <small>{% trans "Sold out" %}</small>
        {% endif %}
    </div>
    <div class="col-4 text-end">
        {% if training_slot.available_registration > 0 %}
            {% if request.user in training_slot.registrations.all %}
            <a href="{% url 'fabcal:trainingslot-unregister' training_slot.pk %}" class="btn btn-outline-primary">{% trans "Unregister" %}</a>
            {% else %}
            <a href="{% url 'fabcal:trainingslot-register' training_slot.pk %}" class="btn btn-primary">{% trans "Register" %}</a>
            {% endif %}
        {% elif training_slot.available_registration == 0 %}
        <button class="btn btn-primary" disabled>{% trans "Register" %}</button>
        {% endif %}
        {% if request.user|has_group:"superuser" %}
            <a href="{% url 'fabcal:trainingslot-update' training_slot.pk %}" class="btn btn-outline-primary my-1"><i class="bi bi-pencil"></i></a>
        {% endif %}
    </div>
    {% endfor %}
    <hr>
</div>
{% endif %}


<div class="row">
    <div class="col-8">
        {% if training_slots %}
            <h3>{% trans "Not available ?" %}</h3>
        {% else %}
            {% trans "Unfortunately, no training planned." %}
        {% endif %}

        {% if not notification %}
        {% trans "We can alert you when a new training is planned." %}
        {%else%}
        {% trans "We will contact you as soon as possible." %}
        {% endif %}
    </div>
    <div class="col-4 mt-auto">
        {% if user.is_authenticated %}
        <form action="." method="post">
            {% csrf_token %}
            {% if notification %}
            <button type="submit" class="btn btn-outline-primary float-end">
                <i class="bi bi-bell-slash pe-2"></i>{% trans "Stop alert me" %}
            </button>
            {% else %}
            <button type="submit" class="btn btn-primary float-end">
                <i class="bi bi-bell-fill pe-2"></i> {% trans "Alert me" %}
            </button>
            {% endif %}
        </form>
        {% else %}
        <a href="{% url 'accounts:login'%}?next={{request.path}}" class="btn btn-outline-primary float-end">
            <i class="bi bi-box-arrow-in-right pe-2"></i> {% trans "Log in" %}
        </a>
        {% endif %}
    </div>
</div>

machines/templates/trainings/show_waiting_list.html
{% load i18n interlab_tags %}

{% if request.user|has_group:"superuser" %}
<hr>
<div class="row mb-4">
    <div class="col-8">
        <h3> {% trans "Waiting list" %} </h3>
        {% blocktranslate with interested_user_count=interested_user_count %} There are {{ interested_user_count }} users interested for this training {% endblocktranslate %}
    </div>
    <div class="col-4 mt-auto">
        <a href={%url 'machines:training-waiting-list' training.pk%} class='btn btn-outline-primary float-end'>
        <i class="bi bi-list-ul pe-2"></i> {% trans "Show users list" %}
        </a>
    </div>
</div>


{% endif %}

machines/templates/trainings/training_validation.html
{% extends "forms/base_forms.html" %}
{% load i18n %}

{% block content_form_img %}
<!-- <i class="bi bi-calendar-check mb-5 img-form-logo mx-auto d-block"></i> -->
<img class="card-img rounded" src="{{training.photo.url}}"  alt="{{training}}">
{% endblock content_form_img %}

{% block content_form %}

<div class="text-center my-2">
    <h3>{% trans "training validation"|capfirst %}</h3>
    <p>
    {{training_slot.training.title}}<br>
    {{training_slot.start|date:"l j F Y"|capfirst}}<br>
</div>
<h4>{% trans "Subscription list: " %}</h4>

<form action="." method="POST">
    {% csrf_token %}
    <div class="row">
    {% for registration in registrations %}
        <div class="col-8">
            {{registration.profile.user.first_name}} {{registration.profile.user.last_name}}
        </div>
        <div class="col-4">
            <div class="form-check form-switch">
                <input class="form-check-input float-end" type="checkbox" role="switch"
                    id={{registration.pk}} name="validations" value="{{registration.profile.pk}}"
                    {% if registration.profile in graduates %}checked{% endif %}>
            </div>
        </div>
        {% endfor %}
        {% include 'forms/base_submit_button.html' with submit_btn=_("Validate training") %}
    </div>
 </form>
    
{% endblock content_form %}

machines/templates/trainings/waiting_list.html
{% extends "base.html" %}
{% load i18n training_extras %}

{% block content %}
<div class="row">
    <div class="col">
        <h1>{% trans "Waiting list for training" %} {{ training.title }}</h1>
    </div>
</div>
{% for training_notification in training_notifications %}
<a class="text-blue" href="{% url 'accounts:superuser-profile-edit' training_notification.profile.user.pk %}">
    <div class="row d-flex justify-content-center">
        <div class="col-3 col-md-1">
            {%include 'accounts/avatar.html' with user=training_notification.profile.user%}
        </div>
        <div class="col-6 col-md-4 my-auto">
            {{training_notification.profile.user.first_name}} {{training_notification.profile.user.last_name}} ({{training_notification.modified_date|date:'d.m.Y'}})       
        </div>
        <div class="col-2 col-md-1 my-auto">
            <h1><i class="bi bi-arrow-right-square"></i></h1>
        </div>
    </div>
</a>
{% endfor %}
{% endblock %}